apiVersion: v1
kind: PersistentVolume
metadata:
  name: comrade-pv
  namespace: comrade-v2
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1M
  hostPath:
    path: /tmp/comrade-v2-pv
