apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comrade-pvc
  namespace: comrade-v2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1M
  storageClassName: ""
