apiVersion: v1
kind: Pod
metadata:
  name: comrade-pod
  namespace: comrade-v2
  labels:
    app: comrade-app
spec:
  volumes:
    - name: comrade-vol
      persistentVolumeClaim:
        claimName: comrade-pvc
  containers:
   - image: itchono/comrade:sha-COMMIT
     name: comrade-container
     imagePullPolicy: Always
  
     envFrom:
       - configMapRef:
           name: comrade-configs

     volumeMounts:
       - name: comrade-vol
         mountPath: /app/data
