name: Publish Docker image
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master   
      - Comrade-V3-dev   
jobs:
    push_to_registry:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
        
          - name: Build & push Docker image to Docker Hub
            uses: docker/build-push-action@v1
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
              repository: itchono/comrade
              cache_froms: itchono/comrade:latest
              tag_with_ref: true
              tag_with_sha: true
