apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-bot-pv
  namespace: music-bot
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1M
  hostPath:
    path: /mnt/sharedfolder/music-bot-pv
