apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-bot-pvc
  namespace: music-bot
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1M
  storageClassName: ""
